// Generated by CoffeeScript 1.3.3
(function() {
  var classes, java, name, root, _i, _len;

  java = require("java");

  java.classpath.push('/Applications/Sikuli-IDE.app/Contents/Resources/Java/sikuli-script.jar');

  root = "org.sikuli.script.";

  classes = ["Settings", "Screen", "Region", "Pattern", "Match", "Finder", "TextRecognizer"];

  for (_i = 0, _len = classes.length; _i < _len; _i++) {
    name = classes[_i];
    exports[name] = java["import"](root + name);
  }

}).call(this);
